post http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Fulasdfjpoadjsf Dev 66556",
    "author": "Ricky populat",
    "url": "https://github.com/RickyUomo",
    "likes": 666,
    "userId": "634c63c4b71a0646ede15d68"
}